version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./dados:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=senha-root
      - MYSQL_DATABASE=nome-do-banco
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=senha-do-usuario
