name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
           java-version: '17'
           distribution: 'temurin'
           cache: maven
           
      - name: Build with Maven
        run: mvn -B package
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build docker image
        run: docker build -t ernilson/vida:1.0.0 .
      - name: Push docker image
        run: docker push ernilson/vida:1.0.0
